globals:
  http:
    client_timeout: 240
  cache:
    base_dir: '/opt/cache'
    lock_dir: '/opt/locks'
    meta_size: [4, 4]
    meta_buffer: 100

  image:
    formats:
      image/png:
        encoding_options:
          quantizer: fastoctree
        mode: P
        transparent: true
    paletted: true
    resampling_method: bicubic
